### PR TITLE
Solved practice 2

### LINKED ISSUE #3: Practice 2 solutions
I would like to work on the solutions of the practice 2 contest 😇

### PR DESCRIPTION
**Pull request by ken1000minus7**
Fixes #3

### CODE REVIEW

**Comment by code-chaser** [comment]
Hey @ken1000minus7,
- please share the links to your submissions on Codeforces,
- plus, can you please rename your files to lowercase characters, `a.kt`, `b.kt`, `c.kt`, `d.kt` 😅. 

Thanks for your patience and sorry for the inconvenience.

**Comment by ken1000minus7** [comment]
Sure @code-chaser  😇 ! There's already an `a.kt` and `c.kt`, should i remove mine? 

Also, I wasn't able to make a submission on codeforces as I was getting this error, don't know why 😕 

image

**Comment by code-chaser** [comment]
Then how will you know your solutions are correct? 😐

**Comment by ken1000minus7** [comment]
I don't see any option to submit 😕

**Pull request closed without merging**
